# ---------------------
# Raspidrink settings
# Use YAML syntax
# ---------------------
# Switch to True if the code is launch from the RPI. Leave False in development
active_gpio: False

# mapping port slot number --> GPIO port number
gpio_mapping:
  0: 26
  1: 4
  2: 17
  3: 27
  4: 22
  5: 5
  6: 6