# ---------------------
# Raspidrink settings
# Use YAML syntax
# ---------------------

# Switch to True if the code is launched from the RPI. Leave False for development as the GPIO lib only works on a Rpi
active_gpio: False

# mapping port. configure your slot in reference to the selected port number over the rpi
# slot number --> GPIO port number
#             --> Time for the pump behind this slot to fill 1 cl
# The slot number 0 is reserved to the Rpi pin that control the reverse relay.
gpio_mapping:
  0:
    pin_number: 21
    time_for_1cl: 1
  1:
    pin_number: 4
    time_for_1cl: 4.8
  2:
    pin_number: 17
    time_for_1cl: 4.8
  3:
    pin_number: 27
    time_for_1cl: 5
  4:
    pin_number: 22
    time_for_1cl: 5.2
  5:
    pin_number: 5
    time_for_1cl: 5.7
  6:
    pin_number: 6
    time_for_1cl: 5
  7:
    pin_number: 13
    time_for_1cl: 4.7
  8:
    pin_number: 19
    time_for_1cl: 6
  9:
    pin_number: 26
    time_for_1cl: 5.1
  10:
    pin_number: 18
    time_for_1cl: 6
  11:
    pin_number: 23
    time_for_1cl: 5.1
  12:
    pin_number: 24
    time_for_1cl: 5
  13:
    pin_number: 25
    time_for_1cl: 4.6
  14:
    pin_number: 12
    time_for_1cl: 5.4
  15:
    pin_number: 16
    time_for_1cl: 4.6
